name: app_well_mate
description: "Ứng dụng chăm sóc sức khoẻ."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_svg: ^1.0.0
  google_fonts: ^6.2.1
  material_symbols_icons: ^4.2758.0
  smooth_page_indicator: ^1.1.0
  intl: ^0.17.0
  provider: ^6.1.2
  json_annotation: ^4.9.0
  syncfusion_flutter_gauges: ^21.2.4
  page_transition: ^2.1.0
  fl_chart: ^0.68.0
  mobile_scanner: ^5.1.1
  simple_barcode_scanner: ^0.1.1
  package_info_plus: ^8.0.0
  animated_custom_dropdown: ^1.0.0
  blur: ^4.0.0
  flutter_local_notifications: ^17.2.1
  timezone: ^0.9.4
  flutter_dotenv: ^5.1.0
  dio: ^5.5.0+1
  flutter_secure_storage: ^9.2.2
  url_launcher: ^6.3.0
  loading_animation_widget: ^1.2.1
  flutter_datetime_picker: ^1.5.1
  snippet_coder_utils: ^1.0.15
  shared_preferences: ^2.2.2
  image_picker: ^1.1.2
  connectivity_plus: ^6.0.3
  android_intent_plus: ^5.0.2
  app_settings: ^5.1.1
  barcode: ^2.2.8
  flutter_paypal_checkout: ^1.0.1
  lottie: ^3.1.2
  notification_listener_service: ^0.3.3
 

flutter_launcher_icons:
  android: true
  image_path: "assets/images/icon/icon.png"
  image_path_android: "assets/images/icon/icon.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_monochrome: "assets/images/icon/monochrome.png"
  adaptive_icon_foreground: "assets/images/icon/foreground.png"

dependency_overrides:
  http: ^0.13.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.11
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/translations/
    - .env
  




  

