name: app_well_mate
description: "Ứng dụng chăm sóc sức khoẻ."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_svg: ^1.0.0
  google_fonts: ^6.2.1
  material_symbols_icons: ^4.2758.0
  smooth_page_indicator: ^1.1.0
  intl: ^0.17.0
  provider: ^6.1.2
  json_annotation: ^4.9.0
  
  syncfusion_flutter_gauges: ^21.2.4
  page_transition: ^2.1.0
  fl_chart: ^0.68.0
  mobile_scanner: ^5.1.1
  simple_barcode_scanner: ^0.1.1
  lottie: ^3.1.2
  flutter_localizations:
    sdk: flutter
  translator: ^0.1.7  

flutter_launcher_icons:
  android: true
  image_path: "assets/images/icon/icon.png"
  image_path_android: "assets/images/icon/icon.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_monochrome: "assets/images/icon/monochrome.png"
  adaptive_icon_foreground: "assets/images/icon/foreground.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.11
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  




  

